name: thepassage
summary: Solve puzzles through debugging and editing parts of real code
description: |
  Ada has landed on a mysterious planet with one mission; find the secret map to locate the hidden bunker. Fight alien monsters, tackle obstacles and puzzles, and hack the world. Debug Javascript puzzles to help Ada create news skills, and navigate obstacles on her way through The Passage.
version: '2.0'
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  thepassage:
    extensions: [gnome]
    command: /The.Passage/The.Passage.x86_64
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  thepassage:
    source: https://github.com/endless-network/ThePassage_Binary/releases/download/v2.0/The.Passage.zip
    plugin: dump
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/The.Passage
      mv $CRAFT_PRIME/'The Passage'/'The Passage.x86_64' $CRAFT_PRIME/The.Passage/The.Passage.x86_64
      mv $CRAFT_PRIME/'The Passage'/'The Passage_Data' $CRAFT_PRIME/The.Passage/'The.Passage_Data'
      rm -r $CRAFT_PRIME/'The Passage'
      chmod +x $CRAFT_PRIME/The.Passage/The.Passage.x86_64
  desktop-files:
    plugin: nil
    source: desktop-file
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp * $CRAFT_PART_INSTALL/meta/gui
